//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 03:19:14 PM ART 
//


package com.monitors.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.monitors.dto.xsd.SmartphoneDetection;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="detection" type="{http://dto.monitors.com/xsd}SmartphoneDetection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "detection"
})
@XmlRootElement(name = "InsertSingleSmartphoneDetectionDTO")
public class InsertSingleSmartphoneDetectionDTO {

    @XmlElementRef(name = "detection", namespace = "http://ws.monitors.com", type = JAXBElement.class, required = false)
    protected JAXBElement<SmartphoneDetection> detection;

    /**
     * Gets the value of the detection property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SmartphoneDetection }{@code >}
     *     
     */
    public JAXBElement<SmartphoneDetection> getDetection() {
        return detection;
    }

    /**
     * Sets the value of the detection property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SmartphoneDetection }{@code >}
     *     
     */
    public void setDetection(JAXBElement<SmartphoneDetection> value) {
        this.detection = value;
    }

}
