//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.07 at 03:19:14 PM ART 
//


package com.monitors.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.monitors.dto.xsd.Device;
import com.monitors.dto.xsd.Frame;
import com.monitors.dto.xsd.SmartphoneDetection;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.monitors.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME = new QName("http://ws.monitors.com", "return");
    private final static QName _InsertSingleDeviceDTODevice_QNAME = new QName("http://ws.monitors.com", "device");
    private final static QName _InsertMultipleFramesData_QNAME = new QName("http://ws.monitors.com", "data");
    private final static QName _InsertSingleSmartphoneDetectionDTODetection_QNAME = new QName("http://ws.monitors.com", "detection");
    private final static QName _InsertSingleFrameDTOFrame_QNAME = new QName("http://ws.monitors.com", "frame");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.monitors.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsertSingleFrameDTO }
     * 
     */
    public InsertSingleFrameDTO createInsertSingleFrameDTO() {
        return new InsertSingleFrameDTO();
    }

    /**
     * Create an instance of {@link InsertSingleDeviceResponse }
     * 
     */
    public InsertSingleDeviceResponse createInsertSingleDeviceResponse() {
        return new InsertSingleDeviceResponse();
    }

    /**
     * Create an instance of {@link InsertMultipleFrameDTOResponse }
     * 
     */
    public InsertMultipleFrameDTOResponse createInsertMultipleFrameDTOResponse() {
        return new InsertMultipleFrameDTOResponse();
    }

    /**
     * Create an instance of {@link InsertSingleDevice }
     * 
     */
    public InsertSingleDevice createInsertSingleDevice() {
        return new InsertSingleDevice();
    }

    /**
     * Create an instance of {@link DeleteDevicesResponse }
     * 
     */
    public DeleteDevicesResponse createDeleteDevicesResponse() {
        return new DeleteDevicesResponse();
    }

    /**
     * Create an instance of {@link InsertMultipleSmartphoneDetection }
     * 
     */
    public InsertMultipleSmartphoneDetection createInsertMultipleSmartphoneDetection() {
        return new InsertMultipleSmartphoneDetection();
    }

    /**
     * Create an instance of {@link InsertSingleSmartphoneDetectionResponse }
     * 
     */
    public InsertSingleSmartphoneDetectionResponse createInsertSingleSmartphoneDetectionResponse() {
        return new InsertSingleSmartphoneDetectionResponse();
    }

    /**
     * Create an instance of {@link InsertSingleSmartphoneDetectionDTOResponse }
     * 
     */
    public InsertSingleSmartphoneDetectionDTOResponse createInsertSingleSmartphoneDetectionDTOResponse() {
        return new InsertSingleSmartphoneDetectionDTOResponse();
    }

    /**
     * Create an instance of {@link InsertMultipleDeviceDTOResponse }
     * 
     */
    public InsertMultipleDeviceDTOResponse createInsertMultipleDeviceDTOResponse() {
        return new InsertMultipleDeviceDTOResponse();
    }

    /**
     * Create an instance of {@link InsertMultipleFrames }
     * 
     */
    public InsertMultipleFrames createInsertMultipleFrames() {
        return new InsertMultipleFrames();
    }

    /**
     * Create an instance of {@link GetDevices }
     * 
     */
    public GetDevices createGetDevices() {
        return new GetDevices();
    }

    /**
     * Create an instance of {@link GetFramesResponse }
     * 
     */
    public GetFramesResponse createGetFramesResponse() {
        return new GetFramesResponse();
    }

    /**
     * Create an instance of {@link DeleteFramesResponse }
     * 
     */
    public DeleteFramesResponse createDeleteFramesResponse() {
        return new DeleteFramesResponse();
    }

    /**
     * Create an instance of {@link InsertMultipleSmartphoneDetectionDTO }
     * 
     */
    public InsertMultipleSmartphoneDetectionDTO createInsertMultipleSmartphoneDetectionDTO() {
        return new InsertMultipleSmartphoneDetectionDTO();
    }

    /**
     * Create an instance of {@link InsertMultipleFrameDTO }
     * 
     */
    public InsertMultipleFrameDTO createInsertMultipleFrameDTO() {
        return new InsertMultipleFrameDTO();
    }

    /**
     * Create an instance of {@link InsertSingleSmartphoneDetectionDTO }
     * 
     */
    public InsertSingleSmartphoneDetectionDTO createInsertSingleSmartphoneDetectionDTO() {
        return new InsertSingleSmartphoneDetectionDTO();
    }

    /**
     * Create an instance of {@link InsertMultipleSmartphoneDetectionDTOResponse }
     * 
     */
    public InsertMultipleSmartphoneDetectionDTOResponse createInsertMultipleSmartphoneDetectionDTOResponse() {
        return new InsertMultipleSmartphoneDetectionDTOResponse();
    }

    /**
     * Create an instance of {@link InsertMultipleDevices }
     * 
     */
    public InsertMultipleDevices createInsertMultipleDevices() {
        return new InsertMultipleDevices();
    }

    /**
     * Create an instance of {@link InsertMultipleSmartphoneDetectionResponse }
     * 
     */
    public InsertMultipleSmartphoneDetectionResponse createInsertMultipleSmartphoneDetectionResponse() {
        return new InsertMultipleSmartphoneDetectionResponse();
    }

    /**
     * Create an instance of {@link InsertSingleFrameResponse }
     * 
     */
    public InsertSingleFrameResponse createInsertSingleFrameResponse() {
        return new InsertSingleFrameResponse();
    }

    /**
     * Create an instance of {@link GetSmartphoneDetectionsResponse }
     * 
     */
    public GetSmartphoneDetectionsResponse createGetSmartphoneDetectionsResponse() {
        return new GetSmartphoneDetectionsResponse();
    }

    /**
     * Create an instance of {@link InsertSingleFrameDTOResponse }
     * 
     */
    public InsertSingleFrameDTOResponse createInsertSingleFrameDTOResponse() {
        return new InsertSingleFrameDTOResponse();
    }

    /**
     * Create an instance of {@link InsertSingleDeviceDTO }
     * 
     */
    public InsertSingleDeviceDTO createInsertSingleDeviceDTO() {
        return new InsertSingleDeviceDTO();
    }

    /**
     * Create an instance of {@link InsertMultipleFramesResponse }
     * 
     */
    public InsertMultipleFramesResponse createInsertMultipleFramesResponse() {
        return new InsertMultipleFramesResponse();
    }

    /**
     * Create an instance of {@link DeleteDevices }
     * 
     */
    public DeleteDevices createDeleteDevices() {
        return new DeleteDevices();
    }

    /**
     * Create an instance of {@link InsertSingleDeviceDTOResponse }
     * 
     */
    public InsertSingleDeviceDTOResponse createInsertSingleDeviceDTOResponse() {
        return new InsertSingleDeviceDTOResponse();
    }

    /**
     * Create an instance of {@link InsertMultipleDeviceDTO }
     * 
     */
    public InsertMultipleDeviceDTO createInsertMultipleDeviceDTO() {
        return new InsertMultipleDeviceDTO();
    }

    /**
     * Create an instance of {@link GetFrames }
     * 
     */
    public GetFrames createGetFrames() {
        return new GetFrames();
    }

    /**
     * Create an instance of {@link InsertSingleSmartphoneDetection }
     * 
     */
    public InsertSingleSmartphoneDetection createInsertSingleSmartphoneDetection() {
        return new InsertSingleSmartphoneDetection();
    }

    /**
     * Create an instance of {@link DeleteFrames }
     * 
     */
    public DeleteFrames createDeleteFrames() {
        return new DeleteFrames();
    }

    /**
     * Create an instance of {@link InsertMultipleDevicesResponse }
     * 
     */
    public InsertMultipleDevicesResponse createInsertMultipleDevicesResponse() {
        return new InsertMultipleDevicesResponse();
    }

    /**
     * Create an instance of {@link InsertSingleFrame }
     * 
     */
    public InsertSingleFrame createInsertSingleFrame() {
        return new InsertSingleFrame();
    }

    /**
     * Create an instance of {@link GetDevicesResponse }
     * 
     */
    public GetDevicesResponse createGetDevicesResponse() {
        return new GetDevicesResponse();
    }

    /**
     * Create an instance of {@link GetSmartphoneDetections }
     * 
     */
    public GetSmartphoneDetections createGetSmartphoneDetections() {
        return new GetSmartphoneDetections();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertSingleSmartphoneDetectionDTOResponse.class)
    public JAXBElement<String> createInsertSingleSmartphoneDetectionDTOResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertSingleSmartphoneDetectionDTOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertMultipleDeviceDTOResponse.class)
    public JAXBElement<String> createInsertMultipleDeviceDTOResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertMultipleDeviceDTOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertSingleSmartphoneDetectionResponse.class)
    public JAXBElement<String> createInsertSingleSmartphoneDetectionResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertSingleSmartphoneDetectionResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Device }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "device", scope = InsertSingleDeviceDTO.class)
    public JAXBElement<Device> createInsertSingleDeviceDTODevice(Device value) {
        return new JAXBElement<Device>(_InsertSingleDeviceDTODevice_QNAME, Device.class, InsertSingleDeviceDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "data", scope = InsertMultipleFrames.class)
    public JAXBElement<String> createInsertMultipleFramesData(String value) {
        return new JAXBElement<String>(_InsertMultipleFramesData_QNAME, String.class, InsertMultipleFrames.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = DeleteFramesResponse.class)
    public JAXBElement<String> createDeleteFramesResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, DeleteFramesResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "data", scope = InsertSingleFrame.class)
    public JAXBElement<String> createInsertSingleFrameData(String value) {
        return new JAXBElement<String>(_InsertMultipleFramesData_QNAME, String.class, InsertSingleFrame.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertMultipleSmartphoneDetectionResponse.class)
    public JAXBElement<String> createInsertMultipleSmartphoneDetectionResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertMultipleSmartphoneDetectionResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertMultipleFramesResponse.class)
    public JAXBElement<String> createInsertMultipleFramesResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertMultipleFramesResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertMultipleDevicesResponse.class)
    public JAXBElement<String> createInsertMultipleDevicesResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertMultipleDevicesResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertMultipleSmartphoneDetectionDTOResponse.class)
    public JAXBElement<String> createInsertMultipleSmartphoneDetectionDTOResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertMultipleSmartphoneDetectionDTOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = DeleteDevicesResponse.class)
    public JAXBElement<String> createDeleteDevicesResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, DeleteDevicesResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "data", scope = InsertMultipleDevices.class)
    public JAXBElement<String> createInsertMultipleDevicesData(String value) {
        return new JAXBElement<String>(_InsertMultipleFramesData_QNAME, String.class, InsertMultipleDevices.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertSingleDeviceDTOResponse.class)
    public JAXBElement<String> createInsertSingleDeviceDTOResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertSingleDeviceDTOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertSingleFrameDTOResponse.class)
    public JAXBElement<String> createInsertSingleFrameDTOResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertSingleFrameDTOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "data", scope = InsertSingleDevice.class)
    public JAXBElement<String> createInsertSingleDeviceData(String value) {
        return new JAXBElement<String>(_InsertMultipleFramesData_QNAME, String.class, InsertSingleDevice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertMultipleFrameDTOResponse.class)
    public JAXBElement<String> createInsertMultipleFrameDTOResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertMultipleFrameDTOResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SmartphoneDetection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "detection", scope = InsertSingleSmartphoneDetectionDTO.class)
    public JAXBElement<SmartphoneDetection> createInsertSingleSmartphoneDetectionDTODetection(SmartphoneDetection value) {
        return new JAXBElement<SmartphoneDetection>(_InsertSingleSmartphoneDetectionDTODetection_QNAME, SmartphoneDetection.class, InsertSingleSmartphoneDetectionDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Frame }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "frame", scope = InsertSingleFrameDTO.class)
    public JAXBElement<Frame> createInsertSingleFrameDTOFrame(Frame value) {
        return new JAXBElement<Frame>(_InsertSingleFrameDTOFrame_QNAME, Frame.class, InsertSingleFrameDTO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertSingleFrameResponse.class)
    public JAXBElement<String> createInsertSingleFrameResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertSingleFrameResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "return", scope = InsertSingleDeviceResponse.class)
    public JAXBElement<String> createInsertSingleDeviceResponseReturn(String value) {
        return new JAXBElement<String>(_InsertSingleSmartphoneDetectionDTOResponseReturn_QNAME, String.class, InsertSingleDeviceResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "data", scope = InsertMultipleSmartphoneDetection.class)
    public JAXBElement<String> createInsertMultipleSmartphoneDetectionData(String value) {
        return new JAXBElement<String>(_InsertMultipleFramesData_QNAME, String.class, InsertMultipleSmartphoneDetection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.monitors.com", name = "data", scope = InsertSingleSmartphoneDetection.class)
    public JAXBElement<String> createInsertSingleSmartphoneDetectionData(String value) {
        return new JAXBElement<String>(_InsertMultipleFramesData_QNAME, String.class, InsertSingleSmartphoneDetection.class, value);
    }

}
